project:
  type: website

website:
  title: "WebGIS"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: open_letter.qmd
        text: Letter
      - Map.qmd
      - Data.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

