project:
  type: website

website:
  title: "Portfolio"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: maps.qmd
        text: Maps
      - href: other_projects.qmd
        text: Coding Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

