project:
  type: website

website:
  title: "William Cornejo's Portfolio"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: maps.qmd
        text: Maps
      #- href: coding.qmd
        #text: Coding Projects
      - href: field.qmd
        text: Field Work

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

