---
title: "Coding Projects"
---

Here are some of my programming-based projects. I mainly branched out to data- analysis related programs for my own research. Most of my work is in Python, Jupyter Notebook, C++, and R.

------------------------------------------------------------------------

## Tree Count Analysis in NYC

Trees are crucial in urban environments as they offer shade, a home for species, and regulate local temperature. Every 10 years in NYC there is a tree count of all trees in New York City. As it is crucial to see how the worsening climate crisis has been affecting the tree life here, the aim of this project is to look at every tree recorded in the NYC Tree count every 10 years and apply geospatial machine learning to predict tree health and areas that need assistance.


**Technologies**: Python, Pandas, scikit, Linear Regression

**Key Features**:

-   Performed exploratory data analysis to clean and interpret data.

-   Applied Logistic Regression and Support Vector Machine models.

-   Severity of a collision is higher when the collision occurs at an intersection.

-   [Kaggle Link](https://www.kaggle.com/code/williamcornejo/evaluating-and-predicting-tree-health-in-nyc)

------------------------------------------------------------------------

## Car Collision Analysis in King County, Washington

Throughout the United States, a significant portion of the population relies on cars for transportation. The objective of this project is to develop a predictive model capable of assessing the likelihood of a car collision. Its primary aim is to offer the safest possible route to a destination. Ultimately, this initiative aims to enhance road safety, benefiting all drivers, whether they are commuting for work or leisure, and ensuring that they can navigate with increased safety compared to current conditions.

**Technologies**: Python, Pandas, Matplotlib, sklearn

**Key Features**:

-   Performed exploratory data analysis to clean and interpret data.

-   Applied Logistic Regression and Support Vector Machine models.

-   Severity of a collision is higher when the collision occurs at an intersection.

-   [GitHub Repository](https://github.com/willm625/Coursera_Capstone)

------------------------------------------------------------------------

## Customer Account Microservice

This project is a secure RESTful API built using Test-Driven Development (TDD) principles, enabling full CRUD operations for user account management. Developed using Agile methodology, it features well-defined user stories and sprint planning. The API is containerized and designed as a microservice with enterprise-level security, including Flask-Talisman headers and Flask-CORS policies. It incorporates modern DevOps practices, such as automated GitHub Actions for continuous integration, Docker for scalability, and Kubernetes for production deployment. With automated tests achieving over 95% coverage and Tekton pipeline integration, this microservice demonstrates end-to-end software engineering, from planning to deployment.

**Technologies**: Docker, Kubernentes, Tekton, Github Actions, Zenhub, Python, Flask

**Key Features**:

-   Developed Agile plan to create RESTful microservice supporting 4 CRUD operations for user.

-   Managed development using Github and Zenhub, completing 25+ user stories in 3 sprints.

-   Created Docker image and deployed microservice to Kubernetes cluster serving 900+ users.

-   Automated work pipeline using Tekton, reducing time from 30 minutes to 3 minutes.

-   [GitHub Repository](https://github.com/willm625/devops-capstone-project)
